version: "3.3"
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: build/db/Dockerfile
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:9.0.0
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=db:5432
      - GF_DATABASE_USER=postgres
      - GF_DATABASE_PASSWORD=postgres
      - GF_DATABASE_SSL_MODE=disable
      - GF_LOG_LEVEL=warn
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
      - GF_INSTALL_PLUGINS=https://github.com/ryantxu/ajax-panel/releases/download/v0.0.6/ryantxu-ajax-panel-0.0.6.zip;ryantxu-ajax-panel
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=ryantxu-ajax-panel
    depends_on:
      - db
    restart: always
    links:
      - db
    ports:
      - "3000:3000"
  trade:
    container_name: trade
    build:
      context: .
      dockerfile: build/trade/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - grafana
    restart: on-failure:3
    links:
      - db
      - grafana
    ports:
      - "8080:8080"
