version: "3.3"
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tinkoff_invest_contest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  trade:
    container_name: trade
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
volumes:
  data:
